#!/bin/bash
chmod +x /replace_address.sh
/replace_address.sh
chmod +x /interface_setup
/interface_setup
: > /etc/resolv.conf
echo "nameserver 10.153.0.53" >> /etc/resolv.conf
ip li add dummy0 type dummy
ip li set dummy0 up
ip addr add 10.0.0.31/32 dev dummy0
[ ! -d /run/bird ] && mkdir /run/bird
bird -d &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

